on:
  push:
    branches:
      - "!release"
name: Run Test Cases
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python_version: ['2.7.18', '3.4.10', '3.5']
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup python
        if: ${{ matrix.python_version != '2.7.18' && matrix.python_version != '3.4.10' }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
          architecture: x64
      - name: Setup python manually
        if: ${{ matrix.python_version == '2.7.18' || matrix.python_version == '3.4.10' }}
        env:
          PYTHON_SOURCE_URL: https://www.python.org/ftp/python/${{ matrix.python_version }}/Python-${{ matrix.python_version }}.tgz
        run: |
          cd /tmp
          curl -s -L "$PYTHON_SOURCE_URL" | tar -zxf - -C ./
          cd Python-${{ matrix.python_version }}
          ./configure --enable-optimizations
          make
          sudo make install
          echo 'export PATH="/opt/python/bin:$PATH"' >> $HOME/.bashrc
      - name: Install dependencies
        run: |
          pip install pytest
      - name: Test
        run: |
          python --version
          python -c "print('Hello Python')"
          pytest test_py.py

