on:
  push:
    branches:
      - "*"
      - "!release"
      - "!test"
name: Run Test Cases
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python_version: ['2.7', '3.4', '3.5']
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge
          python-version: ${{ matrix.python_version }}
          activate-environment: qiniu-sdk
          auto-activate-base: false
      - name: Check pip and python
        shell: bash -l {0}
        env:
          PYTHON_VERSION: ${{ matrix.python_version }}
          PIP_BOOTSTRAP_SCRIPT_PREFIX: https://bootstrap.pypa.io/pip
        run: |
          cd /tmp
          conda info
          conda list
          python --version
          # reinstall pip for compatible
          echo "--- reinstalling pip ---"
          python --version
          MAJOR_MINOR=$(echo $PYTHON_VERSION | cut -d'.' -f1,2)
          wget -qLO get-pip.py "$PIP_BOOTSTRAP_SCRIPT_PREFIX/$MAJOR_MINOR/get-pip.py"
          python get-pip.py --user
          echo "--- reinstalled pip ---"
          python -m pip --version
      - name: Install dependencies
        shell: bash -l {0}
        env:
          PYTHON_VERSION: ${{ matrix.python_version }}
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
      - name: Test
        shell: bash -l {0}
        run: |
          python --version
          python -c "print('Hello Python')"
          type pytest
          pytest test_py.py

